// =============================================================================
// THEME PRESETS — 10 Distinct Roastery Visual Identities
// Each preset is a complete visual system: colors, typography, layout, animation
// =============================================================================

import type { PortalColorTokens, PortalTypography, ThemeVariant, PortalSection } from "../types";
import { DEFAULT_PORTAL_THEME_CONFIG } from "./default-config";

export interface ThemePreset {
  id: string;
  name: string;
  tagline: string;
  preview: string;  // emoji or icon for quick identification
  colors: PortalColorTokens;
  typography: PortalTypography;
  layout: {
    contentWidth: number;
    sectionGap: number;
    pagePadding: number;
    borderRadius: number;
  };
  animations: {
    globalDuration: number;
    globalEasing: string;
    scrollAnimations: boolean;
    hoverEffects: boolean;
  };
  variants: ThemeVariant[];
  sectionDefaults: Record<string, Record<string, unknown>>;  // per-section-type overrides
  defaultSections?: PortalSection[]; // bespoke section layout & bento structure
}

export const THEME_PRESETS: ThemePreset[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 0. ROASTD.ID OFFICIAL — Mirip Landing Page Utama Roastd.id
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "roastr_official",
    name: "Roastd.id Official (Utama)",
    tagline: "Desain resmi roastery — dark premium mirip landing page utama",
    preview: "👑",
    colors: {
      primary: "#B65331",
      secondary: "#15B8C6",
      accent: "#E9A17F",
      background: "#080B0C",
      surface: "#111617",
      surfaceAlt: "#1A1F24",
      text: "#F8FAFC",
      textMuted: "#8B95A5",
      textInverse: "#080B0C",
      border: "rgba(255,255,255,0.1)",
      borderSubtle: "rgba(255,255,255,0.06)",
      error: "#EF4444",
      success: "#22C55E",
      warning: "#F59E0B",
      info: "#38BDF8",
    },
    typography: {
      headingFont: "DM Sans",
      bodyFont: "DM Sans",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.6,
      letterSpacing: -0.02,
      headingWeight: 800,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: {
      contentWidth: 1280,
      sectionGap: 80,
      pagePadding: 24,
      borderRadius: 12,
    },
    animations: {
      globalDuration: 500,
      globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)",
      scrollAnimations: true,
      hoverEffects: true,
    },
    variants: [
      { id: "dark", name: "Dark", isDefault: true, autoSwitch: true, colors: {} },
      { id: "light", name: "Light", isDefault: false, autoSwitch: true, colors: { background: "#FAFAF8", surface: "#FFFFFF", surfaceAlt: "#F5F3EF", text: "#1A1A1A", border: "#E5E5E5" } },
    ],
    sectionDefaults: {
      hero_banner: { overlay: 55, textAlignment: "left" },
      bento_showcase: { columns: 4, gapStyle: "tight" },
      kinetic_marquee: { styleMode: "solid", speed: 28 },
    },
    defaultSections: DEFAULT_PORTAL_THEME_CONFIG.sections,
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // 1. HERITAGE CRAFT — Traditional, warm, artisanal
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "heritage",
    name: "Heritage Craft",
    tagline: "Classic & Artisanal — Timeless coffee tradition",
    preview: "🏺",
    colors: {
      primary: "#8B4513",
      secondary: "#A0522D",
      accent: "#D4A574",
      background: "#FDF8F0",
      surface: "#FFFFFF",
      surfaceAlt: "#F5EDE0",
      text: "#2C1810",
      textMuted: "#8B7355",
      textInverse: "#FDF8F0",
      border: "#E8D5B7",
      borderSubtle: "#F0E6D3",
      error: "#9B2C2C",
      success: "#2D6A4F",
      warning: "#B45309",
      info: "#1E40AF",
    },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 17,
      scaleRatio: 1.333,
      lineHeight: 1.75,
      letterSpacing: 0,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1200, sectionGap: 96, pagePadding: 32, borderRadius: 4 },
    animations: { globalDuration: 800, globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Parchment", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Dark Roast", isDefault: false, autoSwitch: false, colors: { background: "#1A0F0A", surface: "#2C1810", surfaceAlt: "#3D2517", text: "#F5EDE0", textMuted: "#A89279", border: "#4A3020" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "left", overlay: 30 },
      benefits: { columns: 3, iconStyle: "outline" },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. NEO-MODERNIST — Sleek, minimal, contemporary
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "neomodern",
    name: "Neo-Modernist",
    tagline: "Sleek & Minimalist — Clean lines, bold statements",
    preview: "◻️",
    colors: {
      primary: "#1A1A1A",
      secondary: "#404040",
      accent: "#FF6B35",
      background: "#FAFAFA",
      surface: "#FFFFFF",
      surfaceAlt: "#F0F0F0",
      text: "#0A0A0A",
      textMuted: "#737373",
      textInverse: "#FAFAFA",
      border: "#E5E5E5",
      borderSubtle: "#F0F0F0",
      error: "#DC2626",
      success: "#16A34A",
      warning: "#D97706",
      info: "#2563EB",
    },
    typography: {
      headingFont: "Space Grotesk",
      bodyFont: "Inter",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.6,
      letterSpacing: -0.02,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1400, sectionGap: 120, pagePadding: 24, borderRadius: 0 },
    animations: { globalDuration: 500, globalEasing: "cubic-bezier(0.77, 0, 0.175, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Gallery White", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Museum Black", isDefault: false, autoSwitch: false, colors: { background: "#0A0A0A", surface: "#171717", surfaceAlt: "#1F1F1F", text: "#FAFAFA", textMuted: "#A3A3A3", border: "#262626" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "left", overlay: 50 },
      benefits: { columns: 4 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. CYBER-BARISTA — High-tech, futuristic, neon
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "cyber",
    name: "Cyber Barista",
    tagline: "High-Tech & Futuristic — Coffee meets technology",
    preview: "🤖",
    colors: {
      primary: "#00F0FF",
      secondary: "#7B2FFF",
      accent: "#FF006E",
      background: "#0A0A0F",
      surface: "#12121A",
      surfaceAlt: "#1A1A25",
      text: "#E0E0FF",
      textMuted: "#6B6B8A",
      textInverse: "#0A0A0F",
      border: "#2A2A3A",
      borderSubtle: "#1E1E2A",
      error: "#FF4444",
      success: "#00FF88",
      warning: "#FFAA00",
      info: "#00F0FF",
    },
    typography: {
      headingFont: "Orbitron",
      bodyFont: "Inter",
      baseFontSize: 15,
      scaleRatio: 1.2,
      lineHeight: 1.6,
      letterSpacing: 0.05,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1400, sectionGap: 80, pagePadding: 24, borderRadius: 2 },
    animations: { globalDuration: 400, globalEasing: "cubic-bezier(0.77, 0, 0.175, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "dark", name: "Neon Dark", isDefault: true, autoSwitch: false, colors: {} },
      { id: "light", name: "Hologram Light", isDefault: false, autoSwitch: false, colors: { background: "#F0F0FF", surface: "#FFFFFF", surfaceAlt: "#E8E8F8", text: "#0A0A0F", textMuted: "#6B6B8A", border: "#D0D0E0" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "left", overlay: 60 },
      benefits: { columns: 3 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. BOTANICAL LABORATORY — Organic, eco, natural
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "botanical",
    name: "Botanical Lab",
    tagline: "Organic & Eco-Friendly — Nature in every cup",
    preview: "🌿",
    colors: {
      primary: "#2D6A4F",
      secondary: "#40916C",
      accent: "#95D5B2",
      background: "#F7FBF7",
      surface: "#FFFFFF",
      surfaceAlt: "#EDF5ED",
      text: "#1B4332",
      textMuted: "#52796F",
      textInverse: "#F7FBF7",
      border: "#B7E4C7",
      borderSubtle: "#D8F3DC",
      error: "#BC4749",
      success: "#2D6A4F",
      warning: "#E9C46A",
      info: "#264653",
    },
    typography: {
      headingFont: "DM Serif Display",
      bodyFont: "DM Sans",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.7,
      letterSpacing: 0,
      headingWeight: 400,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1280, sectionGap: 100, pagePadding: 28, borderRadius: 16 },
    animations: { globalDuration: 700, globalEasing: "cubic-bezier(0.16, 1, 0.3, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Garden", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Forest Floor", isDefault: false, autoSwitch: false, colors: { background: "#0D1F17", surface: "#162B1E", surfaceAlt: "#1E3528", text: "#D8F3DC", textMuted: "#74C69D", border: "#2D6A4F" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "center", overlay: 25 },
      benefits: { columns: 3 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. EDITORIAL — Storytelling, magazine-like, literary
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "editorial",
    name: "The Roaster's Diary",
    tagline: "Editorial & Storytelling — Every bean has a story",
    preview: "📖",
    colors: {
      primary: "#1A1A1A",
      secondary: "#C9A87C",
      accent: "#D4756B",
      background: "#FFFEF9",
      surface: "#FFFFFF",
      surfaceAlt: "#F8F6F0",
      text: "#1A1A1A",
      textMuted: "#6B6560",
      textInverse: "#FFFEF9",
      border: "#E8E4DA",
      borderSubtle: "#F0ECE3",
      error: "#9B2335",
      success: "#3D7B5F",
      warning: "#C17817",
      info: "#3B6B8A",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Source Serif 4",
      baseFontSize: 18,
      scaleRatio: 1.4,
      lineHeight: 1.8,
      letterSpacing: 0,
      headingWeight: 600,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1100, sectionGap: 110, pagePadding: 36, borderRadius: 8 },
    animations: { globalDuration: 900, globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)", scrollAnimations: true, hoverEffects: false },
    variants: [
      { id: "light", name: "Paper", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Ink", isDefault: false, autoSwitch: false, colors: { background: "#141210", surface: "#1E1C18", surfaceAlt: "#28251F", text: "#F0ECE3", textMuted: "#9A9488", border: "#3A352C" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "left", overlay: 20 },
      rich_text: { alignment: "left" },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. LIQUID SYMPHONY — Fluid, sensory, smooth
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "liquid",
    name: "Liquid Symphony",
    tagline: "Interactive & Sensory — Flow like coffee",
    preview: "💧",
    colors: {
      primary: "#5B4A8A",
      secondary: "#8B6FB0",
      accent: "#E8B4B8",
      background: "#F8F5FA",
      surface: "#FFFFFF",
      surfaceAlt: "#F0ECF5",
      text: "#1A1528",
      textMuted: "#7B6F8A",
      textInverse: "#F8F5FA",
      border: "#DDD5E8",
      borderSubtle: "#EDE8F5",
      error: "#C53030",
      success: "#38A169",
      warning: "#D69E2E",
      info: "#3182CE",
    },
    typography: {
      headingFont: "Outfit",
      bodyFont: "Nunito",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.7,
      letterSpacing: 0,
      headingWeight: 600,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1280, sectionGap: 90, pagePadding: 28, borderRadius: 24 },
    animations: { globalDuration: 1000, globalEasing: "cubic-bezier(0.16, 1, 0.3, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Lavender Mist", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Deep Violet", isDefault: false, autoSwitch: false, colors: { background: "#0E0A14", surface: "#1A1425", surfaceAlt: "#221C30", text: "#EDE8F5", textMuted: "#9B8FB0", border: "#2D2540" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "center", overlay: 35 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. INDUSTRIAL ALCHEMY — Gritty, bold, raw
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "industrial",
    name: "Industrial Alchemy",
    tagline: "Gritty & Bold — Raw craftsmanship",
    preview: "⚙️",
    colors: {
      primary: "#D97706",
      secondary: "#92400E",
      accent: "#FCD34D",
      background: "#1C1917",
      surface: "#292524",
      surfaceAlt: "#3A3533",
      text: "#F5F5F4",
      textMuted: "#A8A29E",
      textInverse: "#1C1917",
      border: "#44403C",
      borderSubtle: "#292524",
      error: "#EF4444",
      success: "#22C55E",
      warning: "#EAB308",
      info: "#3B82F6",
    },
    typography: {
      headingFont: "Oswald",
      bodyFont: "Work Sans",
      baseFontSize: 15,
      scaleRatio: 1.2,
      lineHeight: 1.6,
      letterSpacing: 0.03,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1400, sectionGap: 80, pagePadding: 24, borderRadius: 2 },
    animations: { globalDuration: 400, globalEasing: "cubic-bezier(0.65, 0, 0.35, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "dark", name: "Forge", isDefault: true, autoSwitch: false, colors: {} },
      { id: "light", name: "Workshop", isDefault: false, autoSwitch: false, colors: { background: "#FAF9F7", surface: "#FFFFFF", surfaceAlt: "#F5F3EF", text: "#1C1917", textMuted: "#78716C", border: "#E7E5E4" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "left", overlay: 55 },
      benefits: { columns: 2 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. COFFEE CLUB — Community, warm, inviting
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "club",
    name: "Coffee Club",
    tagline: "Subscription & Community — Join the circle",
    preview: "☕",
    colors: {
      primary: "#B45309",
      secondary: "#92400E",
      accent: "#F59E0B",
      background: "#FFFBEB",
      surface: "#FFFFFF",
      surfaceAlt: "#FEF3C7",
      text: "#1C1917",
      textMuted: "#78716C",
      textInverse: "#FFFBEB",
      border: "#FDE68A",
      borderSubtle: "#FEF3C7",
      error: "#DC2626",
      success: "#16A34A",
      warning: "#D97706",
      info: "#2563EB",
    },
    typography: {
      headingFont: "Fredoka",
      bodyFont: "Nunito",
      baseFontSize: 16,
      scaleRatio: 1.3,
      lineHeight: 1.7,
      letterSpacing: 0,
      headingWeight: 600,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1200, sectionGap: 88, pagePadding: 28, borderRadius: 20 },
    animations: { globalDuration: 600, globalEasing: "cubic-bezier(0.34, 1.56, 0.64, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Morning Brew", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Evening Blend", isDefault: false, autoSwitch: false, colors: { background: "#1C1208", surface: "#2A1D0F", surfaceAlt: "#352514", text: "#FEF3C7", textMuted: "#D4A054", border: "#4A3520" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "center", overlay: 30 },
      benefits: { columns: 4 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. LUXURY RESERVE — Elite, ultra-premium, sophisticated
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "luxury",
    name: "Luxury Reserve",
    tagline: "Elite & Ultra-Premium — The finest selection",
    preview: "👑",
    colors: {
      primary: "#1A1A1A",
      secondary: "#333333",
      accent: "#C9A96E",
      background: "#FAFAF8",
      surface: "#FFFFFF",
      surfaceAlt: "#F5F4F0",
      text: "#0A0A0A",
      textMuted: "#6B6B6B",
      textInverse: "#FAFAF8",
      border: "#E5E4E0",
      borderSubtle: "#F0EFEB",
      error: "#9B1C1C",
      success: "#047857",
      warning: "#B45309",
      info: "#1E40AF",
    },
    typography: {
      headingFont: "Cormorant",
      bodyFont: "Jost",
      baseFontSize: 17,
      scaleRatio: 1.35,
      lineHeight: 1.7,
      letterSpacing: 0.08,
      headingWeight: 600,
      bodyWeight: 300,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1100, sectionGap: 120, pagePadding: 40, borderRadius: 0 },
    animations: { globalDuration: 1000, globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)", scrollAnimations: true, hoverEffects: false },
    variants: [
      { id: "light", name: "Ivory", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Obsidian", isDefault: false, autoSwitch: false, colors: { background: "#0A0A0A", surface: "#141414", surfaceAlt: "#1C1C1C", text: "#F5F4F0", textMuted: "#8A8A8A", border: "#2A2A2A" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "center", overlay: 40 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. PLAYFUL BREW — Vibrant, pop art, fun
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "playful",
    name: "Playful Brew",
    tagline: "Vibrant & Pop Art — Coffee is fun!",
    preview: "🎉",
    colors: {
      primary: "#E11D48",
      secondary: "#7C3AED",
      accent: "#FBBF24",
      background: "#FFF1F2",
      surface: "#FFFFFF",
      surfaceAlt: "#FFF1F2",
      text: "#1F1235",
      textMuted: "#6B7280",
      textInverse: "#FFF1F2",
      border: "#FECDD3",
      borderSubtle: "#FFE4E6",
      error: "#DC2626",
      success: "#16A34A",
      warning: "#F59E0B",
      info: "#3B82F6",
    },
    typography: {
      headingFont: "Baloo 2",
      bodyFont: "Quicksand",
      baseFontSize: 16,
      scaleRatio: 1.3,
      lineHeight: 1.65,
      letterSpacing: 0,
      headingWeight: 800,
      bodyWeight: 500,
      textTransform: "none",
    },
    layout: { contentWidth: 1200, sectionGap: 80, pagePadding: 24, borderRadius: 24 },
    animations: { globalDuration: 500, globalEasing: "cubic-bezier(0.34, 1.56, 0.64, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Berry Pop", isDefault: true, autoSwitch: false, colors: {} },
      { id: "dark", name: "Neon Night", isDefault: false, autoSwitch: false, colors: { background: "#1F1235", surface: "#2A1A45", surfaceAlt: "#352055", text: "#FFF1F2", textMuted: "#B0A0C0", border: "#4A3570" } },
    ],
    sectionDefaults: {
      hero_banner: { textAlignment: "center", overlay: 25 },
      benefits: { columns: 3 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 11. NEO-TOKYO CYBER BARISTA — OLED Dark Mode, Tech Bento Grid, Monospace
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "neo_tokyo_cyber",
    name: "Neo-Tokyo Cyber Barista",
    tagline: "OLED Cyberpunk & Precision Tech — High-contrast neon aesthetics",
    preview: "⚡",
    colors: {
      primary: "#F97316",
      secondary: "#06B6D4",
      accent: "#D4A574",
      background: "#090D16",
      surface: "#111827",
      surfaceAlt: "#1F2937",
      text: "#F8FAFC",
      textMuted: "#94A3B8",
      textInverse: "#090D16",
      border: "#334155",
      borderSubtle: "#1E293B",
      error: "#EF4444",
      success: "#10B981",
      warning: "#F59E0B",
      info: "#3B82F6",
    },
    typography: {
      headingFont: "JetBrains Mono",
      bodyFont: "Inter",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.6,
      letterSpacing: 0.02,
      headingWeight: 800,
      bodyWeight: 400,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1280, sectionGap: 64, pagePadding: 24, borderRadius: 16 },
    animations: { globalDuration: 400, globalEasing: "cubic-bezier(0.16, 1, 0.3, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "dark", name: "Cyber OLED", isDefault: true, autoSwitch: false, colors: {} },
    ],
    sectionDefaults: {
      bento_showcase: { columns: 4, gapStyle: "tight" },
      marquee_kinetic: { speed: 20, styleMode: "neon" },
    },
    defaultSections: [
      {
        id: "sec_cyber_header",
        type: "header_nav",
        enabled: true,
        settings: { styleMode: "cyber_dock", logoText: "ROASTD.ID", tickerText: "🚀 FREE NATIONWIDE SHIPPING ON ORDERS OVER 5KG • WEEKLY ROASTING SCHEDULE: TUE & THU", ctaText: "Wholesale Cart" },
        blocks: [],
      },
      {
        id: "sec_cyber_marquee",
        type: "marquee_kinetic",
        enabled: true,
        settings: { speed: 20, styleMode: "neon", direction: "left" },
        blocks: [
          { id: "m1", type: "text_item", visible: true, settings: { text: "⚡ LORING S70 AUTOMATED PROFILES" } },
          { id: "m2", type: "text_item", visible: true, settings: { text: "🟢 SYSTEM ONLINE // NITROGEN FLUSHED" } },
          { id: "m3", type: "text_item", visible: true, settings: { text: "🔒 BLOCKCHAIN TRACEABILITY 0.02MS" } },
          { id: "m4", type: "text_item", visible: true, settings: { text: "☕ AI THERMAL ROAST PREDICTION" } },
        ],
      },
      {
        id: "sec_cyber_hero",
        type: "hero_banner",
        enabled: true,
        settings: {
          title: "CYBERNETIC ROAST CONTROL",
          subtitle: "Precision thermal profiling & nitrogen-flushed packaging for next-gen B2B coffee enterprises.",
          buttonText: "CONNECT TELEMETRY",
          buttonLink: "#catalog",
          overlay: 50,
          textAlignment: "center",
        },
        background: { type: "color", color: "#090D16", textureType: "grid", textureOpacity: 40 },
        blocks: [],
      },
      {
        id: "sec_cyber_bento",
        type: "bento_showcase",
        enabled: true,
        settings: {
          title: "SYSTEM ARCHITECTURE",
          subtitle: "Real-time roasting telemetry and automated supply chain contracts",
          columns: 4,
          gapStyle: "tight",
        },
        background: { type: "color", color: "#111827" },
        blocks: [
          {
            id: "cb1",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 2,
            settings: {
              title: "LORING S70 AUTOMATED PROFILES",
              subtitle: "Closed-loop nitrogen convection roasting ensures zero oxygen degradation and precise crack development.",
              content: "Live telemetry streaming bean core temperature at 0.02ms accuracy across all commercial lots.",
              badge: "SYSTEM ACTIVE 🟢",
              accentColor: "#F97316",
              icon: "Activity",
            },
          },
          {
            id: "cb2",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 1,
            settings: {
              title: "THERMAL CURVE AI",
              subtitle: "Predictive bean temperature modeling",
              content: "Machine learning algorithms prevent tipping and scorching.",
              badge: "TELEMETRY",
              accentColor: "#06B6D4",
              icon: "Cpu",
            },
          },
          {
            id: "cb3",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "88.5+ SCA AVERAGE",
              subtitle: "Q-Grade verified microlots",
              content: "Certified by 3 independent Q-graders.",
              badge: "SCORE",
              accentColor: "#10B981",
              icon: "CheckCircle2",
            },
          },
          {
            id: "cb4",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "0.02ms TRACEABILITY",
              subtitle: "Smart contract farm ledger",
              content: "Direct payment confirmation to washing stations.",
              badge: "BLOCKCHAIN",
              accentColor: "#3B82F6",
              icon: "ShieldCheck",
            },
          },
        ],
      },
      {
        id: "sec_cyber_catalog",
        type: "catalog_grid",
        enabled: true,
        settings: {
          title: "ACTIVE LOT INVENTORY",
          subtitle: "Live warehouse stock ready for automated dispatch",
          columns: 3,
          productFilter: "all",
          sortBy: "name",
        },
        blocks: [],
      },
      {
        id: "sec_cyber_footer",
        type: "footer_nav",
        enabled: true,
        settings: { styleMode: "cyber_terminal", logoText: "ROASTD.ID", bioText: "Empowering specialty coffee roasters and B2B cafe partners with precision telemetry, micro-batch profiling, and direct-trade sourcing.", copyrightText: "© 2026 ROASTD.ID • Roastery Operating System. All rights reserved." },
        blocks: [],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 12. NORDIC BOTANICAL ALCHEMY — Soft Sage, Liquid Transitions, White Space
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "nordic_botanical",
    name: "Nordic Botanical Alchemy",
    tagline: "Soft Sage & Organic Minimalism — Calming Scandinavian fluidity",
    preview: "🌿",
    colors: {
      primary: "#4F6E58",
      secondary: "#8F9E8B",
      accent: "#C5B393",
      background: "#F7F9F6",
      surface: "#FFFFFF",
      surfaceAlt: "#EEF2ED",
      text: "#2D3730",
      textMuted: "#6B7D70",
      textInverse: "#FFFFFF",
      border: "#DCE3DD",
      borderSubtle: "#E9EEEA",
      error: "#DC2626",
      success: "#16A34A",
      warning: "#D97706",
      info: "#2563EB",
    },
    typography: {
      headingFont: "Outfit",
      bodyFont: "Plus Jakarta Sans",
      baseFontSize: 16,
      scaleRatio: 1.3,
      lineHeight: 1.7,
      letterSpacing: 0,
      headingWeight: 600,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1200, sectionGap: 100, pagePadding: 32, borderRadius: 28 },
    animations: { globalDuration: 700, globalEasing: "cubic-bezier(0.34, 1.56, 0.64, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "Sage Day", isDefault: true, autoSwitch: false, colors: {} },
    ],
    sectionDefaults: {
      bento_showcase: { columns: 3, gapStyle: "relaxed" },
      interactive_flavor: { subtitle: "Explore our sustainably farmed organic lots." },
    },
    defaultSections: [
      {
        id: "sec_bot_header",
        type: "header_nav",
        enabled: true,
        settings: { styleMode: "scandi_minimal", logoText: "ROASTD.ID", tickerText: "🌿 SUSTAINABLY GROWN • DIRECT TRADE HEIRLOOM LOTS", ctaText: "Wholesale Cart" },
        blocks: [],
      },
      {
        id: "sec_bot_hero",
        type: "hero_banner",
        enabled: true,
        settings: {
          title: "Pure Botanical Alchemy",
          subtitle: "Sustainably farmed, shade-grown heirloom coffees cultivated in harmony with native forest canopies.",
          buttonText: "Explore Harvests",
          buttonLink: "#catalog",
          overlay: 20,
          textAlignment: "left",
        },
        background: { type: "color", color: "#F0F4F1", textureType: "grain", textureOpacity: 25 },
        blocks: [],
      },
      {
        id: "sec_bot_bento",
        type: "bento_showcase",
        enabled: true,
        settings: {
          title: "Our Organic Ecosystem",
          subtitle: "From high-altitude Ethiopian cloud forests to solar-powered roasting facilities in Bandung",
          columns: 3,
          gapStyle: "relaxed",
        },
        background: { type: "color", color: "#E6EDE8" },
        blocks: [
          {
            id: "bb1",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 2,
            settings: {
              title: "SHADE-GROWN ETHIOPIAN HEIRLOOM",
              subtitle: "Hand-picked under wild forest canopies in Yirgacheffe, preserving biodiversity and slow bean maturation.",
              content: "Our organic agroforestry model supports 400+ smallholder farming families with guaranteed premium pricing.",
              badge: "ORGANIC 🌱",
              accentColor: "#4F6E58",
              icon: "Leaf",
            },
          },
          {
            id: "bb2",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 2,
            settings: {
              title: "SOLAR ROASTING",
              subtitle: "100% renewable thermal energy facility",
              content: "Zero carbon footprint across all roasting and packaging operations.",
              badge: "ECO",
              accentColor: "#74C69D",
              icon: "Sun",
            },
          },
          {
            id: "bb3",
            type: "bento_card",
            visible: true,
            colSpan: 3,
            rowSpan: 1,
            settings: {
              title: "REGENERATIVE SOIL SANCTUARY",
              subtitle: "Direct-to-farmer harvesting protocol with zero synthetic pesticides or chemical fertilizers.",
              content: "Restoring soil microbiome health through natural composting and cover cropping.",
              badge: "SANCTUARY",
              accentColor: "#8F9E8B",
              icon: "Globe",
            },
          },
        ],
      },
      {
        id: "sec_bot_flavor",
        type: "interactive_flavor",
        enabled: true,
        settings: {
          title: "Sensory Profile Matrix",
          subtitle: "Filter our seasonal microlots by dominant flavor notes and botanical aroma",
        },
        blocks: [],
      },
      {
        id: "sec_bot_catalog",
        type: "catalog_grid",
        enabled: true,
        settings: {
          title: "Seasonal Harvest Collection",
          subtitle: "Single-origin coffees roasted daily in small batches",
          columns: 3,
          productFilter: "all",
          sortBy: "name",
        },
        blocks: [],
      },
      {
        id: "sec_bot_footer",
        type: "footer_nav",
        enabled: true,
        settings: { styleMode: "minimal_centered", logoText: "ROASTD.ID", bioText: "Cultivating organic, shade-grown coffee lots in harmony with native forest canopies.", copyrightText: "© 2026 ROASTD.ID • Sustainable Roastery System." },
        blocks: [],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 13. TACTILE BRUTALIST ROASTERY — 1px Borders, Neo-Grotesk, Ticker Focus
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "tactile_brutalist",
    name: "Tactile Brutalist Roastery",
    tagline: "Raw Industrial & High-Contrast — Unapologetic neo-grotesk grid",
    preview: "⬛",
    colors: {
      primary: "#000000",
      secondary: "#222222",
      accent: "#E2FE00",
      background: "#FFFFFF",
      surface: "#F4F4F4",
      surfaceAlt: "#EAEAEA",
      text: "#000000",
      textMuted: "#555555",
      textInverse: "#FFFFFF",
      border: "#000000",
      borderSubtle: "#333333",
      error: "#FF0000",
      success: "#00CC44",
      warning: "#FF9900",
      info: "#0066FF",
    },
    typography: {
      headingFont: "Syne",
      bodyFont: "Space Grotesk",
      baseFontSize: 16,
      scaleRatio: 1.4,
      lineHeight: 1.5,
      letterSpacing: -0.02,
      headingWeight: 800,
      bodyWeight: 500,
      textTransform: "uppercase",
    },
    layout: { contentWidth: 1400, sectionGap: 48, pagePadding: 20, borderRadius: 0 },
    animations: { globalDuration: 300, globalEasing: "cubic-bezier(0, 0, 0.2, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "light", name: "High Contrast", isDefault: true, autoSwitch: false, colors: {} },
    ],
    sectionDefaults: {
      marquee_kinetic: { speed: 15, styleMode: "brutalist" },
      bento_showcase: { gapStyle: "tight" },
    },
    defaultSections: [
      {
        id: "sec_brut_header",
        type: "header_nav",
        enabled: true,
        settings: { styleMode: "industrial_ticker", logoText: "ROASTD.ID", tickerText: "⚡ INDUSTRIAL GRADE WHOLESALE ROASTING // NO BS COFFEE ⚡", ctaText: "Wholesale Cart" },
        blocks: [],
      },
      {
        id: "sec_brut_marquee_top",
        type: "marquee_kinetic",
        enabled: true,
        settings: { speed: 15, styleMode: "brutalist", direction: "left" },
        blocks: [
          { id: "bm1", type: "text_item", visible: true, settings: { text: "RAW INDUSTRIAL COFFEE SUPPLY //" } },
          { id: "bm2", type: "text_item", visible: true, settings: { text: "NO BULLSHIT ROASTING //" } },
          { id: "bm3", type: "text_item", visible: true, settings: { text: "100% DIRECT TRADE ARABICA //" } },
          { id: "bm4", type: "text_item", visible: true, settings: { text: "SHIPPED DAILY NATIONWIDE //" } },
        ],
      },
      {
        id: "sec_brut_hero",
        type: "hero_banner",
        enabled: true,
        settings: {
          title: "HEAVY DUTY WHOLESALE COFFEE",
          subtitle: "Unapologetic consistency and high-yield extraction for high-volume commercial espresso bars.",
          buttonText: "LOCK CONTRACT",
          buttonLink: "#catalog",
          overlay: 10,
          textAlignment: "left",
        },
        background: { type: "color", color: "#E2FE00" },
        blocks: [],
      },
      {
        id: "sec_brut_bento",
        type: "bento_showcase",
        enabled: true,
        settings: {
          title: "SPECIFICATION MATRIX",
          subtitle: "Industrial roasting parameters engineered for maximum yield and zero waste",
          columns: 3,
          gapStyle: "tight",
        },
        background: { type: "color", color: "#000000" },
        blocks: [
          {
            id: "br1",
            type: "bento_card",
            visible: true,
            colSpan: 3,
            rowSpan: 1,
            settings: {
              title: "WHOLESALE VOLUME CONTRACTS // 100KG - 10,000KG",
              subtitle: "Price locked for 12 months with guaranteed weekly automated warehouse dispatch and priority logistics.",
              content: "No unexpected surcharge. Priority green coffee allocation locked upon contract signature.",
              badge: "CONTRACT #88",
              accentColor: "#E2FE00",
              icon: "Package",
            },
          },
          {
            id: "br2",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 2,
            settings: {
              title: "ZERO COMPROMISE",
              subtitle: "Strict 86+ SCA minimum on all commercial house blends.",
              content: "No robusta fillers. Pure Arabica density.",
              badge: "SPEC // 01",
              accentColor: "#FFFFFF",
              icon: "ShieldCheck",
            },
          },
          {
            id: "br3",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 2,
            settings: {
              title: "THE LORING S70 WORKHORSE",
              subtitle: "Consistent bean development from first crack to drop with digital airflow profiling.",
              content: "Automated PID burners ensure zero variation between daily production runs.",
              badge: "MACHINE // S70",
              accentColor: "#E2FE00",
              icon: "Flame",
            },
          },
        ],
      },
      {
        id: "sec_brut_radar",
        type: "roast_matrix",
        enabled: true,
        settings: {
          title: "VOLUME CONTRACT SIMULATOR",
          subtitle: "Calculate your monthly wholesale tier discount and cupping profile comparison",
        },
        blocks: [],
      },
      {
        id: "sec_brut_catalog",
        type: "catalog_grid",
        enabled: true,
        settings: {
          title: "COMMERCIAL BLENDS & MICROLOTS",
          subtitle: "Order in 1kg, 5kg, or 20kg bulk commercial buckets",
          columns: 3,
          productFilter: "all",
          sortBy: "name",
        },
        blocks: [],
      },
      {
        id: "sec_brut_footer",
        type: "footer_nav",
        enabled: true,
        settings: { styleMode: "brutalist_mono", logoText: "ROASTD.ID", bioText: "High-contrast industrial coffee roasting for modern B2B hospitality.", copyrightText: "© 2026 ROASTD.ID // ALL RIGHTS RESERVED." },
        blocks: [],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 14. LIQUID SENSORY SYMPHONY — Glassmorphism, Mesh Gradients, Flavor Focus
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "liquid_sensory",
    name: "Liquid Sensory Symphony",
    tagline: "Glassmorphism & Warm Amber Glow — Sensory-first fluidity",
    preview: "🔮",
    colors: {
      primary: "#D4A574",
      secondary: "#B65331",
      accent: "#F59E0B",
      background: "#0F1117",
      surface: "#181B26",
      surfaceAlt: "#222736",
      text: "#F3F4F6",
      textMuted: "#9CA3AF",
      textInverse: "#0F1117",
      border: "#2D3446",
      borderSubtle: "#1F2432",
      error: "#EF4444",
      success: "#10B981",
      warning: "#F59E0B",
      info: "#3B82F6",
    },
    typography: {
      headingFont: "Cabinet Grotesk",
      bodyFont: "Inter",
      baseFontSize: 16,
      scaleRatio: 1.25,
      lineHeight: 1.65,
      letterSpacing: 0,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1280, sectionGap: 80, pagePadding: 24, borderRadius: 24 },
    animations: { globalDuration: 650, globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "dark", name: "Liquid Amber", isDefault: true, autoSwitch: false, colors: {} },
    ],
    sectionDefaults: {
      interactive_flavor: { title: "Liquid Sensory Symphony" },
    },
    defaultSections: [
      {
        id: "sec_liq_header",
        type: "header_nav",
        enabled: true,
        settings: { styleMode: "glass_pill", logoText: "ROASTD.ID", tickerText: "🔮 EXPERIENCE THE AMBER LIQUID SENSORY COLLECTION", ctaText: "Tasting Bag" },
        blocks: [],
      },
      {
        id: "sec_liq_hero",
        type: "hero_banner",
        enabled: true,
        settings: {
          title: "The Amber Liquid Experience",
          subtitle: "Sensory-first espresso profiles and rare competition microlots crafted for modern hospitality.",
          buttonText: "Experience Tasting Notes",
          buttonLink: "#flavor-wheel",
          overlay: 30,
          textAlignment: "center",
        },
        background: { type: "color", color: "#161224", textureType: "glass", textureOpacity: 50 },
        blocks: [],
      },
      {
        id: "sec_liq_flavor",
        type: "interactive_flavor",
        enabled: true,
        settings: {
          title: "Interactive Sensory Wheel",
          subtitle: "Click a flavor note to reveal calibrated coffee lots matching that exact aromatic profile",
        },
        background: { type: "color", color: "#1E1833" },
        blocks: [],
      },
      {
        id: "sec_liq_bento",
        type: "bento_showcase",
        enabled: true,
        settings: {
          title: "Sensory Architecture",
          subtitle: "How we manipulate water chemistry, thermal convection, and extraction geometry",
          columns: 3,
          gapStyle: "normal",
        },
        background: { type: "color", color: "#161224", textureType: "glass", textureOpacity: 40 },
        blocks: [
          {
            id: "lb1",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 2,
            settings: {
              title: "SYRUPY MOUTHFEEL & CLEAN FINISH",
              subtitle: "Our signature espresso calibration protocol emphasizes lipid preservation and sweetness balance.",
              content: "Careful heat modulation during Maillard reaction maximizes soluble sucrose density.",
              badge: "SENSORY ✨",
              accentColor: "#D4A574",
              icon: "Sparkles",
            },
          },
          {
            id: "lb2",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "JASMINE & BERGAMOT",
              subtitle: "Washed Geisha microlot",
              content: "Harvested at 1,950m in Volcan, Panama.",
              badge: "FLAVOR",
              accentColor: "#F59E0B",
              icon: "Coffee",
            },
          },
          {
            id: "lb3",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "DARK COCOA NIBS",
              subtitle: "70/30 Espresso Blend",
              content: "Rich crema and persistent chocolate finish in milk.",
              badge: "FLAVOR",
              accentColor: "#B65331",
              icon: "Coffee",
            },
          },
          {
            id: "lb4",
            type: "bento_card",
            visible: true,
            colSpan: 3,
            rowSpan: 1,
            settings: {
              title: "CUPPING PROTOCOL COMPLIANT",
              subtitle: "Calibrated weekly by Q-Graders to ensure zero flavor drift across seasonal lot transitions.",
              content: "Rigorous water TDS matching and grind distribution analysis for every wholesale partner.",
              badge: "QUALITY",
              accentColor: "#8B5CF6",
              icon: "Award",
            },
          },
        ],
      },
      {
        id: "sec_liq_catalog",
        type: "catalog_grid",
        enabled: true,
        settings: {
          title: "Curated Sensory Collection",
          subtitle: "Order tasting flights and commercial espresso boxes",
          columns: 3,
          productFilter: "all",
          sortBy: "name",
        },
        blocks: [],
      },
      {
        id: "sec_liq_footer",
        type: "footer_nav",
        enabled: true,
        settings: { styleMode: "editorial_grid", logoText: "ROASTD.ID", bioText: "Sensory-first espresso profiles and rare competition microlots crafted for modern hospitality.", copyrightText: "© 2026 ROASTD.ID • Liquid Symphony." },
        blocks: [],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 15. HERITAGE RESERVE — Editorial Magazine Layout, Gold Foil, Sticky Scroll
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "heritage_reserve",
    name: "Heritage Reserve",
    tagline: "Editorial Luxury & Gold Foil Accents — B2B prestige storytelling",
    preview: "👑",
    colors: {
      primary: "#C5A059",
      secondary: "#1A231C",
      accent: "#E5C158",
      background: "#0D120F",
      surface: "#141C17",
      surfaceAlt: "#1C2720",
      text: "#F4F1EA",
      textMuted: "#9EAA9F",
      textInverse: "#0D120F",
      border: "#2D3B31",
      borderSubtle: "#1E2821",
      error: "#EF4444",
      success: "#10B981",
      warning: "#F59E0B",
      info: "#3B82F6",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Montserrat",
      baseFontSize: 16,
      scaleRatio: 1.333,
      lineHeight: 1.75,
      letterSpacing: 0.01,
      headingWeight: 700,
      bodyWeight: 400,
      textTransform: "none",
    },
    layout: { contentWidth: 1200, sectionGap: 96, pagePadding: 32, borderRadius: 8 },
    animations: { globalDuration: 800, globalEasing: "cubic-bezier(0.22, 1, 0.36, 1)", scrollAnimations: true, hoverEffects: true },
    variants: [
      { id: "dark", name: "Reserve Dark", isDefault: true, autoSwitch: false, colors: {} },
    ],
    sectionDefaults: {
      sticky_narrative: { pinnedTitle: "Heritage Reserve", pinnedSubtitle: "100 Year Tradition" },
    },
    defaultSections: [
      {
        id: "sec_her_header",
        type: "header_nav",
        enabled: true,
        settings: { styleMode: "luxury_editorial", logoText: "ROASTD.ID", tickerText: "👑 PRIVATE ESTATE ALLOCATIONS & CENTURY ROASTING TRADITION", ctaText: "Reserve Bag" },
        blocks: [],
      },
      {
        id: "sec_her_hero",
        type: "hero_banner",
        enabled: true,
        settings: {
          title: "Heritage Reserve Roastery",
          subtitle: "A century of artisanal coffee tradition and private estate selections for discerning B2B purveyors.",
          buttonText: "Request Allocation",
          buttonLink: "#catalog",
          overlay: 40,
          textAlignment: "center",
        },
        background: { type: "color", color: "#141414", textureType: "grain", textureOpacity: 35 },
        blocks: [],
      },
      {
        id: "sec_her_sticky",
        type: "sticky_narrative",
        enabled: true,
        settings: {
          title: "The Century Tradition",
          subtitle: "How we curate the world's most exclusive coffee harvests",
          pinnedTitle: "PRIVATE RESERVE",
          pinnedSubtitle: "ESTABLISHED 1924 // ESTABLISHED PURVEYORS",
        },
        background: { type: "color", color: "#1A1A1A" },
        blocks: [
          {
            id: "hs1",
            type: "narrative_step",
            visible: true,
            settings: {
              title: "01. High-Altitude Volcanic Selection",
              subtitle: "We partner exclusively with century-old family estates situated above 1,800 meters.",
              content: "Nutrient-dense volcanic soil imparts extraordinary complex acidity and density to our heirloom varieties.",
              tag: "ALTITUDE",
              year: "1,850m ASL",
              location: "Antigua, Guatemala",
            },
          },
          {
            id: "hs2",
            type: "narrative_step",
            visible: true,
            settings: {
              title: "02. Traditional Slow-Drum Roasting",
              subtitle: "Cast-iron vintage roasting drums restored with modern digital thermal sensors.",
              content: "Allowing us to develop rich caramelization without scorching delicate floral notes.",
              tag: "CRAFT",
              year: "1954 Vintage Drum",
              location: "Master Roaster Calibration",
            },
          },
          {
            id: "hs3",
            type: "narrative_step",
            visible: true,
            settings: {
              title: "03. Private Vault Storage & Dispatch",
              subtitle: "Green beans are rested in temperature-controlled humidity vaults.",
              content: "Roasted to order in bespoke numbered foil pouches for luxury hospitality purveyors.",
              tag: "VAULT",
              year: "100% Nitrogen Flush",
              location: "Direct Luxury Logistics",
            },
          },
        ],
      },
      {
        id: "sec_her_bento",
        type: "bento_showcase",
        enabled: true,
        settings: {
          title: "PRIVATE ESTATE LOTS",
          subtitle: "Exclusive regional allocations for luxury hotels and fine dining establishments",
          columns: 4,
          gapStyle: "normal",
        },
        background: { type: "color", color: "#141414" },
        blocks: [
          {
            id: "hb1",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 2,
            settings: {
              title: "PRIVATE ESTATE ALLOCATION",
              subtitle: "Exclusive territorial rights and custom bag branding for 5-star hospitality partners.",
              content: "Bespoke roast profile development and dedicated Q-Grader account manager assigned to your venue.",
              badge: "RESERVE 👑",
              accentColor: "#C5A059",
              icon: "Award",
            },
          },
          {
            id: "hb2",
            type: "bento_card",
            visible: true,
            colSpan: 2,
            rowSpan: 1,
            settings: {
              title: "GOLD SELECTION ESPRESSO",
              subtitle: "100% High-grown Arabica from volcanic soil",
              content: "Balanced notes of wild honey, toasted hazelnut, and dark cherry.",
              badge: "SIGNATURE",
              accentColor: "#E5C158",
              icon: "Coffee",
            },
          },
          {
            id: "hb3",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "91.0 SCA RATING",
              subtitle: "Certified Q-Grade lot",
              content: "Exceptional cup cleanliness and acidity.",
              badge: "SCORE",
              accentColor: "#10B981",
              icon: "CheckCircle2",
            },
          },
          {
            id: "hb4",
            type: "bento_card",
            visible: true,
            colSpan: 1,
            rowSpan: 1,
            settings: {
              title: "LIMITED ALLOCATION",
              subtitle: "Only 100 kg available",
              content: "Reserved for contract partners.",
              badge: "RARE",
              accentColor: "#C5A059",
              icon: "ShieldCheck",
            },
          },
        ],
      },
      {
        id: "sec_her_catalog",
        type: "catalog_grid",
        enabled: true,
        settings: {
          title: "The Reserve Collection",
          subtitle: "Order bespoke private reserve lots and custom hospitality blends",
          columns: 3,
          productFilter: "all",
          sortBy: "name",
        },
        blocks: [],
      },
      {
        id: "sec_her_footer",
        type: "footer_nav",
        enabled: true,
        settings: { styleMode: "editorial_grid", logoText: "ROASTD.ID", bioText: "A century of artisanal coffee tradition and private estate selections for discerning B2B purveyors.", copyrightText: "© 2026 ROASTD.ID • Heritage Reserve Roastery." },
        blocks: [],
      },
    ],
  },
];

// ── Helper ──────────────────────────────────────────────────────────────────

export function getThemePresetById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}

export function getThemePresetNames(): Array<{ id: string; name: string; tagline: string; preview: string }> {
  return THEME_PRESETS.map(({ id, name, tagline, preview }) => ({ id, name, tagline, preview }));
}
