import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { prisma } from "@/lib/prisma";
import { requireCurrentUser } from "@/lib/auth";
import { computeScaTotal, scaGrade } from "@/lib/cupping-intelligence";
import { CUPPING_CATEGORIES, loadSessionSummary } from "@/lib/cupping-summary";

export const dynamic = "force-dynamic";

interface RouteContext {
  params: Promise<{ sessionId: string }>;
}

export async function GET(_request: Request, context: RouteContext) {
  const user = await requireCurrentUser();
  const { sessionId } = await context.params;

  const session = await prisma.cuppingSession.findFirst({
    where: { id: sessionId, tenantId: user.tenantId },
    include: { scores: true },
  });
  if (!session) {
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }

  const summary = await loadSessionSummary(sessionId, user.tenantId);
  if (!summary) {
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`Cupping Session — ${session.code}`, margin, margin + 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80);
  const dateStr = session.date.toLocaleDateString("id-ID", { timeZone: "Asia/Jakarta" });
  const lines = [
    `Evaluator: ${session.evaluatorName ?? "(unnamed)"}`,
    `Date: ${dateStr}`,
    `Defects: ${session.defectCount ?? 0}`,
    `Total Score (T): ${summary.totalScore.toFixed(2)}`,
    `Grade: ${summary.gradeLabel}`,
  ];
  lines.forEach((line, index) => {
    doc.text(line, margin, margin + 28 + index * 14);
  });

  const tableRows = CUPPING_CATEGORIES.map((category) => [
    category.replace(/_/g, " "),
    summary.categoryAverages[category].toFixed(2),
  ]);
  // Sanity check: recompute the composite live to catch any drift.
  const recomputed = computeScaTotal(summary.categoryAverages, session.defectCount ?? 0);
  const drift = Math.abs(recomputed - summary.totalScore);
  if (drift > 0.01) {
    tableRows.push(["Composite (recomputed)", recomputed.toFixed(2)]);
    tableRows.push(["Drift", drift.toFixed(2)]);
  }

  autoTable(doc, {
    startY: margin + 28 + lines.length * 14 + 12,
    head: [["Category", "Score"]],
    body: tableRows,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [169, 71, 40], textColor: 255 },
  });

  if (session.notes) {
    const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 320;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20);
    doc.text("Notes", margin, finalY + 24);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60);
    const noteLines = doc.splitTextToSize(session.notes, 480);
    doc.text(noteLines, margin, finalY + 40);
  }

  // Sign-off footer: deterministic summary string for auditability.
  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text(
    `Generated by roastd.id · ${new Date().toISOString()} · grade=${scaGrade(summary.totalScore)}`,
    margin,
    doc.internal.pageSize.height - 24,
  );

  const pdf = doc.output("arraybuffer");
  return new NextResponse(pdf, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="cupping-${session.code}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}