import Link from "next/link";
import { AlertTriangle, ArrowRight, BadgeCheck, Boxes, Factory, FileSignature, Flame, PackageCheck, Radar, ShieldCheck, TrendingUp, Warehouse } from "lucide-react";

import { PageHeader } from "@/components/layout/PageHeader";
import { getControlTowerData } from "./actions";

export const dynamic = "force-dynamic";

const number = new Intl.NumberFormat("id-ID", { maximumFractionDigits: 2 });
const currency = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });

function Metric({ label, value, detail, tone = "cyan" }: { label: string; value: string; detail: string; tone?: "cyan" | "amber" | "green" | "purple" }) {
  const colors = { cyan: "border-cyan-200 bg-cyan-50 text-cyan-950", amber: "border-amber-200 bg-amber-50 text-amber-950", green: "border-emerald-200 bg-emerald-50 text-emerald-950", purple: "border-purple-200 bg-purple-50 text-purple-950" }[tone];
  return <div className={`rounded-2xl border p-4 ${colors}`}><p className="text-[11px] font-bold uppercase tracking-[0.12em] opacity-60">{label}</p><p className="mt-2 text-2xl font-black tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs leading-5 opacity-65">{detail}</p></div>;
}

function SectionHeading({ icon, eyebrow, title, detail, href, action }: { icon: React.ReactNode; eyebrow: string; title: string; detail: string; href?: string; action?: string }) {
  return <div className="flex flex-wrap items-end justify-between gap-3 border-b border-stone-200 px-5 py-4"><div className="flex min-w-0 gap-3"><span className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-[#0B141B] text-cyan-300">{icon}</span><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-stone-400">{eyebrow}</p><h2 className="mt-0.5 text-base font-black tracking-[-0.02em] text-stone-950">{title}</h2><p className="mt-1 text-xs leading-5 text-stone-500">{detail}</p></div></div>{href && action ? <Link href={href} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-stone-300 px-3 text-xs font-bold text-stone-700 hover:bg-stone-50">{action}<ArrowRight size={13} /></Link> : null}</div>;
}

function EmptyRow({ children }: { children: React.ReactNode }) { return <div className="px-5 py-8 text-center text-sm text-stone-500">{children}</div>; }

export default async function ControlTowerPage() {
  const data = await getControlTowerData();
  const production = data.plan.finishedGoods.filter((row) => row.suggestedProduction > 0);
  const roast = data.plan.materials.filter((row) => row.kind === "ROASTED_BEAN" && row.shortage > 0);
  const green = data.plan.materials.filter((row) => row.kind === "GREEN_BEAN" && row.shortage > 0);
  const supplies = data.plan.supplies.filter((row) => row.shortage > 0);
  const readyChecks = data.readiness.filter((row) => row.ready).length;

  return <div className="flex min-h-0 flex-1 flex-col bg-[#F6F6F1]">
    <PageHeader title="Control Tower" eyebrow="Operasional" description="Pesanan → posisi stok → kebutuhan produksi → roasting → pembelian. Rekomendasi bersifat read-only dan tetap memerlukan keputusan manusia." />
    <main className="custom-scrollbar flex-1 overflow-auto"><div className="mx-auto max-w-[1500px] space-y-5 p-4 md:p-6 lg:p-8">
      <section aria-label="Ringkasan rekomendasi" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric label="Produksi disarankan" value={`${number.format(data.plan.summary.productionUnits)} unit`} detail={`${data.plan.summary.productionSkuCount} SKU dengan resep siap dieksekusi.`} tone="amber" />
        <Metric label="Output roast dibutuhkan" value={`${number.format(data.plan.summary.roastOutputKg)} kg`} detail={`${data.plan.summary.roastSkuCount} roasted bean perlu ditutup.`} />
        <Metric label="SKU perlu dibeli" value={number.format(data.plan.summary.purchaseSkuCount)} detail="Green bean, roasted bean beli-jadi, atau supply setelah PO aktif diperhitungkan." tone="purple" />
        <Metric label="Kesiapan konfigurasi" value={`${readyChecks}/${data.readiness.length}`} detail="Pemeriksaan master data, gudang, checkout, dan storefront." tone="green" />
      </section>

      <div className="rounded-2xl border border-cyan-200 bg-cyan-50 px-5 py-4 text-sm leading-6 text-cyan-950"><strong>Rumus keputusan:</strong> posisi persediaan = stok fisik + sisa PO − stok terikat. Kebutuhan terkonfirmasi tidak dihitung dua kali dengan forecast; safety stock dan lead time tetap dipertahankan.</div>

      <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm">
        <SectionHeading icon={<Factory size={17} />} eyebrow="Batch 9 · Demand" title="Rencana produksi produk jadi" detail="Urutan berdasarkan kekurangan terbesar. Produk tanpa resep tetap terlihat sebagai blocker, bukan dihitung dengan asumsi." href="/produksi" action="Buka produksi" />
        {production.length === 0 ? <EmptyRow>Tidak ada produksi tambahan yang disarankan saat ini.</EmptyRow> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-stone-50 text-[10px] uppercase tracking-[0.1em] text-stone-500"><tr><th className="px-5 py-3">Produk</th><th className="px-3 py-3 text-right">Pesanan</th><th className="px-3 py-3 text-right">Terikat</th><th className="px-3 py-3 text-right">Stok + PO</th><th className="px-3 py-3 text-right">Safety</th><th className="px-3 py-3 text-right">Saran</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-stone-100">{production.map((row) => <tr key={row.productId} className="hover:bg-stone-50/70"><td className="px-5 py-3"><strong className="block text-sm text-stone-900">{row.name}</strong><span className="font-mono text-[10px] text-stone-400">{row.code}</span></td><td className="px-3 py-3 text-right">{number.format(row.openDemand)}</td><td className="px-3 py-3 text-right">{number.format(row.committed)}</td><td className="px-3 py-3 text-right">{number.format(row.onHand + row.onOrder)}</td><td className="px-3 py-3 text-right">{number.format(row.safetyStock)}</td><td className="px-3 py-3 text-right text-base font-black text-amber-700">{number.format(row.suggestedProduction)}</td><td className="px-5 py-3">{row.hasRecipe ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 font-bold text-emerald-700">Resep siap</span> : <span className="rounded-full bg-red-50 px-2.5 py-1 font-bold text-red-700">Resep belum ada</span>}</td></tr>)}</tbody></table></div>}
      </section>

      <div className="grid gap-5 xl:grid-cols-2">
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<Flame size={17} />} eyebrow="Batch 11 · Roast" title="Kebutuhan roasting" detail="Kebutuhan RB diturunkan dari resep produk jadi dan dikonversi ke input GB memakai yield historis." href="/roasting" action="Buka roasting" />{roast.length === 0 ? <EmptyRow>Tidak ada tambahan roasting yang disarankan.</EmptyRow> : <ul className="divide-y divide-stone-100">{roast.map((row) => <li key={row.productId} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div><strong className="text-sm text-stone-900">{row.name}</strong><p className="mt-1 text-xs text-stone-500">Butuh output {number.format(row.shortage)} kg · yield {number.format((row.yieldRate ?? 0) * 100)}%</p></div><div className="text-right"><p className="text-lg font-black text-[#B65331]">{number.format(row.suggestedRoastInputKg)} kg</p><p className="text-[10px] uppercase tracking-wide text-stone-400">input GB</p></div></li>)}</ul>}</section>
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<Boxes size={17} />} eyebrow="Batch 9 · Material" title="Kebutuhan pembelian" detail="Sisa PO dan penerimaan parsial dikurangkan sebelum rekomendasi dibuat." href="/inventory?view=po" action="Buka PO" />{green.length + supplies.length === 0 ? <EmptyRow>Tidak ada pembelian tambahan yang disarankan.</EmptyRow> : <ul className="divide-y divide-stone-100">{green.map((row) => <li key={row.productId} className="flex items-center justify-between gap-4 px-5 py-3"><div><strong className="text-sm text-stone-900">{row.name}</strong><p className="text-xs text-stone-500">Green bean · stok {number.format(row.onHand)} kg · PO {number.format(row.onOrder)} kg</p></div><strong className="text-sm text-purple-700">Beli {number.format(row.shortage)} kg</strong></li>)}{supplies.map((row) => <li key={row.supplyItemId} className="flex items-center justify-between gap-4 px-5 py-3"><div><strong className="text-sm text-stone-900">{row.name}</strong><p className="text-xs text-stone-500">Stok {number.format(row.onHand)} · PO {number.format(row.onOrder)} {row.baseUnit}</p></div><strong className="text-sm text-purple-700">Beli {number.format(row.shortage)} {row.baseUnit}</strong></li>)}</ul>}</section>
      </div>

      <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<PackageCheck size={17} />} eyebrow="Order priority" title="Pesanan yang harus ditindaklanjuti" detail="Urutan jatuh tempo lalu waktu terbit; satu sumber dari Invoice dan fulfillment task." href="/penjualan/fulfillment" action="Buka fulfillment" />{data.orders.length === 0 ? <EmptyRow>Semua pesanan aktif sudah selesai ditindaklanjuti.</EmptyRow> : <ul className="divide-y divide-stone-100">{data.orders.map((order) => <li key={order.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href="/penjualan" className="font-black text-stone-900 hover:underline">{order.code}</Link><span className="rounded-full bg-stone-100 px-2 py-0.5 text-[10px] font-bold uppercase text-stone-600">{order.status}</span>{order.shortageUnits > 0 ? <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-700">Kurang {order.shortageUnits} unit</span> : null}</div><p className="mt-1 truncate text-xs text-stone-500">{order.customer} · {order.channel.replaceAll("_", " ")}</p></div><div className="text-right"><strong className="text-sm text-stone-800">{currency.format(order.value)}</strong><p className="mt-1 text-[10px] text-stone-400">{order.dueDate ? `Jatuh tempo ${new Date(order.dueDate).toLocaleDateString("id-ID")}` : `Masuk ${new Date(order.issuedAt).toLocaleDateString("id-ID")}`}</p></div></li>)}</ul>}</section>
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<ShieldCheck size={17} />} eyebrow="Production readiness" title="Gate sebelum scale" detail={`${readyChecks} dari ${data.readiness.length} pemeriksaan konfigurasi lulus.`} /><ul className="divide-y divide-stone-100">{data.readiness.map((check) => <li key={check.key} className="flex gap-3 px-5 py-3"><span className={`mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full ${check.ready ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{check.ready ? <BadgeCheck size={14} /> : <AlertTriangle size={13} />}</span><div className="min-w-0 flex-1"><Link href={check.href} className="text-xs font-bold text-stone-900 hover:underline">{check.label}</Link><p className="mt-0.5 text-[11px] leading-4 text-stone-500">{check.detail}</p></div></li>)}</ul></section>
      </div>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<Warehouse size={17} />} eyebrow="Batch 10" title="Warehouse & FEFO" detail="Eksekusi lokasi dan risiko kedaluwarsa." href="/gudang" action="Gudang" /><div className="grid grid-cols-3 gap-2 p-4 text-center"><div><strong className="text-xl text-stone-900">{data.warehouse.expiringLots.length}</strong><p className="text-[10px] text-stone-500">lot ≤30 hari</p></div><div><strong className="text-xl text-stone-900">{data.warehouse.unplacedLotCount}</strong><p className="text-[10px] text-stone-500">belum ditempatkan</p></div><div><strong className="text-xl text-red-700">{data.warehouse.latePoCount}</strong><p className="text-[10px] text-stone-500">PO terlambat</p></div></div>{data.warehouse.expiringLots.length ? <ul className="border-t border-stone-100">{data.warehouse.expiringLots.slice(0, 3).map((lot) => <li key={lot.id} className="px-4 py-2.5 text-xs"><strong className="text-stone-800">{lot.item}</strong><p className="mt-0.5 text-stone-500">{lot.batchCode} · {new Date(lot.expiryDate).toLocaleDateString("id-ID")} · {number.format(lot.remaining)} {lot.unit}</p></li>)}</ul> : null}</section>
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<Radar size={17} />} eyebrow="Batch 11" title="Quality intelligence" detail="QC tetap opsional, tetapi gap terlihat." href="/cupping" action="Cupping" /><div className="space-y-3 p-4 text-xs"><p className="flex justify-between"><span className="text-stone-500">Roast aktif</span><strong>{data.quality.openRoastCount}</strong></p><p className="flex justify-between"><span className="text-stone-500">Tanpa cupping 30 hari</span><strong>{data.quality.completedWithoutCupping}</strong></p><p className="flex justify-between"><span className="text-stone-500">Yield rata-rata</span><strong>{data.quality.averageYieldPercent === null ? "Belum ada data" : `${number.format(data.quality.averageYieldPercent)}%`}</strong></p><p className="flex justify-between"><span className="text-stone-500">Artisan sync</span><strong className={data.quality.artisanEnabled ? "text-emerald-700" : "text-stone-500"}>{data.quality.artisanEnabled ? "Aktif" : "Opsional / nonaktif"}</strong></p></div></section>
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<FileSignature size={17} />} eyebrow="Batch 12" title="B2B command" detail="Kontrak, omzet, dan risiko piutang." href="/penjualan/kontrak" action="Kontrak" /><div className="space-y-3 p-4 text-xs"><p className="flex justify-between"><span className="text-stone-500">Kontrak aktif</span><strong>{data.b2b.activeContracts}</strong></p><p className="flex justify-between"><span className="text-stone-500">Berakhir ≤30 hari</span><strong>{data.b2b.expiringContracts}</strong></p><p className="flex justify-between"><span className="text-stone-500">Omzet B2B 30 hari</span><strong>{currency.format(data.b2b.sales30Days)}</strong></p><p className="flex justify-between"><span className="text-stone-500">Piutang terlambat</span><strong className="text-red-700">{data.b2b.overdueReceivables} · {currency.format(data.b2b.overdueValue)}</strong></p></div></section>
        <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><SectionHeading icon={<TrendingUp size={17} />} eyebrow="Batch 13" title="Profit intelligence" detail="Revenue dan HPP snapshot dari barang terkirim." href="/laporan/analisa/laba-rugi" action="Laporan" /><div className="space-y-3 p-4 text-xs"><p className="flex justify-between"><span className="text-stone-500">Revenue 30 hari</span><strong>{currency.format(data.finance.revenue30Days)}</strong></p><p className="flex justify-between"><span className="text-stone-500">Laba kotor</span><strong>{currency.format(data.finance.grossProfit30Days)}</strong></p><p className="flex justify-between"><span className="text-stone-500">Margin kotor</span><strong>{data.finance.grossMarginPercent === null ? "Belum ada data" : `${number.format(data.finance.grossMarginPercent)}%`}</strong></p><p className="flex justify-between"><span className="text-stone-500">SKU rugi</span><strong className={data.finance.lossMakingSkus.length ? "text-red-700" : "text-emerald-700"}>{data.finance.lossMakingSkus.length}</strong></p></div></section>
      </div>
      <p className="pb-2 text-center text-[10px] text-stone-400">Dihitung {new Date(data.generatedAt).toLocaleString("id-ID")} · Semua rekomendasi dapat ditelusuri kembali ke transaksi canonical.</p>
    </div></main>
  </div>;
}
